version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: schooldb
    volumes:
      - ./initializeDb/setupTables.sql:/docker-entrypoint-initdb.d/setupTables.sql
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "python manage.py initialization && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/schoolApi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL : mysql://root:my-secret-pw@db:3306/schoolDb
    depends_on:
      - db

volumes:
  initializeDb:


