# Generated by Django 4.1.4 on 2023-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryTable',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('notes', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'history_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('item_code', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_condition', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventory_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_of_reservation', models.DateField()),
                ('date_of_expiration', models.DateField()),
                ('claim', models.IntegerField()),
            ],
            options={
                'db_table': 'reservation_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_table',
                'managed': False,
            },
        ),
    ]
