# Generated by Django 4.1.4 on 2023-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'role_table',
                'managed': False,
            },
        ),
    ]
